#!/bin/sh
# Copyright (c) 2020 Aron Xu <aron@debian.org>

set -e
WORKDIR=build
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM

NUM_CPU=$(nproc)
NJOBS="-j $NUM_CPU"

make $NJOBS check VERBOSE=1

rm -rf $WORKDIR
exit 0
